coverage:
    status:
        project:
            default:
                informational: true
        patch:
            default:
                informational: true  # Avoid failing PRs when new code reduces coverage
